apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app:healthservice
  template:
    metadata:
      labels:
        app: healthservice
    spec:
      containers:
      - name: healthservice
        image: aksh193/healthservice:latest
        ports:
        - containerPort: 8080
    apiVersion: v1
    kind: Service
     metadata:
  name: healthservice
   spec:
  type: LoadBalancer
  selector:
    app: healthservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
