name: Basic Testing

on:
  push:
    branches:
      - master
      - staging
  workflow_dispatch:

jobs:
  Test_and_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Maven test
        run: mvn test

      - name: Checkstyle
        run: mvn checkstyle:checkstyle

      - name: Maven build
        run: mv clean package